### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by tomdebuyser** [GetStream/stream-dolby-voxeet#1]
Hello,

I wanted to checkout the demo at https://stream-dolby.netlify.app/ but it is not doing anything after login. Also if I add a second participant nothing is happening. I am just getting a green-blue screen with an icon in the center.

Is this application still working properly?

Thanks

**Comment by tbarbugli** [comment]
@nparsons08 looks like we hit some API quota for the demo account

**Comment by astrotars** [comment]
@tomdebuyser we are working on getting this fixed as soon as possible. I'll reply within the next 24-48 hours when it is fixed! Thank you for bringing this up :) CC/ @yetieaterxb1

**Comment by yetieaterxb1** [comment]
@tomdebuyser its all set!
